baseURL = ""
relativeURLs = true
title = "Survey Solutions"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

defaultContentLanguageInSubdir = "true"
DefaultContentLanguage = "en"

[languages]
    [languages.en]
    LanguageName = "English"

    [languages.ru]
    LanguageName = "Русский"

    [languages.es]
    LanguageName = "Español"

    [languages.fr]
    LanguageName =  "Français"

    [languages.ar]
    LanguageName = "العربية"

    [languages.pt]
    LanguageName = "Português"

    [languages.zh]
    LanguageName = "中文"


[params]
LatestVersion = "20.10"
releaseNotesLink = "https://support.mysurvey.solutions/release-notes/version-20-10/"
contactformurl = "https://pds.mysurvey.solutions/ContactUs"
downloadLink = "https://pds.mysurvey.solutions/api/apps/installer/latest"
versionFromPortal = "https://pds.mysurvey.solutions/api/apps/release"
demoArticleLink = "https://support.mysurvey.solutions/headquarters/config/demo-server/"