baseURL = "https://mysurvey.solutions/"
title = "Survey Solutions"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

defaultContentLanguageInSubdir = "true"
DefaultContentLanguage = "en"

[languages]
    [languages.en]
    LanguageName = "English"

    [languages.ru]
    LanguageName = "Русский"

    [languages.es]
    LanguageName = "Español"

    [languages.fr]
    LanguageName =  "Français"

    [languages.ar]
    LanguageName = "العربية"

    [languages.pt]
    LanguageName = "Português"

    [languages.zh]
    LanguageName = "中文"


[params]
LatestVersion = "20.09"
releaseNotesLink = "https://support.mysurvey.solutions/release-notes/version-20.09/"
contactformurl = "https://mysurvey.solutions/ContactUs"
downloadLink = "https://mysurvey.solutions/api/apps/installer/latest"